# yaml-language-server: $schema=https://raw.githubusercontent.com/vivekkumardev8/ripple/main/ripple.schema.json
paths:
  'src/api/**': vivekkumardev8
  'src/db/**': vivekkumardev8
  'src/services/**': vivekkumardev8
  'src/lib/**': vivekkumardev8
